# Production context: all deploys from the Production branch set in your siteâ€™s
# deploy contexts will inherit these settings.
# [context.production]
#   publish = "result/bin/frontend.jsexe/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
